### ISSUE TITLE
Outdated urls and author info in package.json

### ISSUE THREAD

**Issue by drauggres** [DeviceFarmer/adbkit-logcat#11]
Subj

https://github.com/DeviceFarmer/adbkit-logcat/blob/307b1c51d3fe5465bdc6062aaf577725a0fa032c/package.json#L11
https://github.com/DeviceFarmer/adbkit-logcat/blob/307b1c51d3fe5465bdc6062aaf577725a0fa032c/package.json#L22
https://github.com/DeviceFarmer/adbkit-logcat/blob/307b1c51d3fe5465bdc6062aaf577725a0fa032c/package.json#L14-L18

**Comment by koral--** [comment]
Thanks for the report.
FYI we haven't proactively updated all the metadata in all the repos forked from OpenSTF yet.
In general update happens just before nearest release.
Another thing is that DeviceFarmer has no separate official e-mail address yet at the time of writing.

**Comment by koral--** [comment]
Updated
